// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3hnX60oEtXE71D3ecOoUJMyTejy1cbis',
    appId: '1:503576786444:web:eea4947c5c323715e02029',
    messagingSenderId: '503576786444',
    projectId: 'softride-d144d',
    authDomain: 'softride-d144d.firebaseapp.com',
    storageBucket: 'softride-d144d.appspot.com',
    measurementId: 'G-67MHZH7TDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDggtH9Km2fxP6LlmLQu85o74-bKqk5UP4',
    appId: '1:503576786444:android:49fe9d5110414a60e02029',
    messagingSenderId: '503576786444',
    projectId: 'softride-d144d',
    storageBucket: 'softride-d144d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM-OyXppH69WRypFMIps5sTmUvrNxlqGs',
    appId: '1:503576786444:ios:d551305a8a2f491de02029',
    messagingSenderId: '503576786444',
    projectId: 'softride-d144d',
    storageBucket: 'softride-d144d.appspot.com',
    iosClientId: '503576786444-f1bi1bceamddgiqlfignim0tcug292t8.apps.googleusercontent.com',
    iosBundleId: 'com.example.softRide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM-OyXppH69WRypFMIps5sTmUvrNxlqGs',
    appId: '1:503576786444:ios:dbf002af23b090b1e02029',
    messagingSenderId: '503576786444',
    projectId: 'softride-d144d',
    storageBucket: 'softride-d144d.appspot.com',
    iosClientId: '503576786444-rv8rsmmvcbjs1gfciund4ki9l2nandgl.apps.googleusercontent.com',
    iosBundleId: 'com.example.softRide.RunnerTests',
  );
}
